openapi: 3.0.3
info:
  title: Procure-to-Pay API
  version: 1.0.0
  description: API documentation for the Procure-to-Pay system.
paths:
  /api/requests/:
    get:
      operationId: requests_list
      tags:
      - requests
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseRequest'
          description: ''
    post:
      operationId: requests_create
      tags:
      - requests
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PurchaseRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PurchaseRequest'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseRequest'
          description: ''
  /api/requests/{id}/:
    get:
      operationId: requests_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this purchase request.
        required: true
      tags:
      - requests
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseRequest'
          description: ''
    put:
      operationId: requests_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this purchase request.
        required: true
      tags:
      - requests
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PurchaseRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PurchaseRequest'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseRequest'
          description: ''
    patch:
      operationId: requests_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this purchase request.
        required: true
      tags:
      - requests
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPurchaseRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPurchaseRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPurchaseRequest'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseRequest'
          description: ''
    delete:
      operationId: requests_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this purchase request.
        required: true
      tags:
      - requests
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    PatchedPurchaseRequest:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        description:
          type: string
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        status:
          $ref: '#/components/schemas/StatusEnum'
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        proforma:
          type: string
          format: uri
          nullable: true
        purchase_order:
          type: string
          format: uri
          nullable: true
        receipt:
          type: string
          format: uri
          nullable: true
        created_by:
          type: integer
        approved_by:
          type: integer
          nullable: true
    PurchaseRequest:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        description:
          type: string
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        status:
          $ref: '#/components/schemas/StatusEnum'
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        proforma:
          type: string
          format: uri
          nullable: true
        purchase_order:
          type: string
          format: uri
          nullable: true
        receipt:
          type: string
          format: uri
          nullable: true
        created_by:
          type: integer
        approved_by:
          type: integer
          nullable: true
      required:
      - amount
      - created_at
      - created_by
      - description
      - id
      - title
      - updated_at
    StatusEnum:
      enum:
      - pending
      - approved
      - rejected
      type: string
      description: |-
        * `pending` - Pending
        * `approved` - Approved
        * `rejected` - Rejected
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
